### ISSUE TITLE
Blacklist / filter out specific maps

### ISSUE THREAD

**Issue by Fort-TM** [SilPho/medal-collection#6]
Certain maps that are listed in the Played category are impossible to finish (e.g. the lobby maps for Bonk Cup), so it would be good to have an advanced option to filter out these maps (the user could input the map UID to filter it)

This idea came while talking about the plugin with Airwam on Discord

![image](https://github.com/user-attachments/assets/95ead5fb-87fd-4050-bd4a-270f396ba960)

**Comment by SilPho** [comment]
I can see this being useful for other maps that a player would have no hope of finishing. I know my own collection includes Deep Dip 2, which will remain unfinished forever.

I'm imagining a button that appears when you click the random map button on an unfinished map, so it might look a bit like this:
![image](https://github.com/user-attachments/assets/3efbd35a-cc70-46c4-8b5d-69687808ff2b)

This isn't a true ignore-list, since it would delete the entry from your personal list, and only for maps without a medal (because they might end up returning anyway).

Does this sound like it would fulfill your needs?

**Comment by Fort-TM** [comment]
Yes, that would be perfect. Removing it from the personal list is fine in my opinion since having such maps doesn't serve any purposes if they are unbeatable/impossible for us

Thanks for the quick response too!

**Comment by SilPho** [comment]
This feature is now available in Version 2.4 and above. Thanks for the suggestion :)

**Comment by Fort-TM** [comment]
Thanks for the quick implementation!
